"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, BookOpen, Check, ChevronRight, CircleHelp, Clock3, Download, FileText, LockKeyhole, Play, Target, Video } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { ProgressBar } from "@/components/ui";
import { useCourseUnits } from "@/lib/hooks";
import { getLearningStats, readState, writeState, type UnitPdfRecord } from "@/lib/store";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";
import { CourseImage } from "@/components/course-image";
import { demoFileUrl } from "@/lib/demo-files";

export default function UnitPage(){
 const params=useParams<{unitId:string}>(); const courseUnits=useCourseUnits(); const unit=courseUnits.find(x=>x.id===Number(params.unitId));
 const [completed,setCompleted]=useState<string[]>([]); const [pdf,setPdf]=useState<UnitPdfRecord|undefined>(undefined); const [pdfUrl,setPdfUrl]=useState<string|undefined>(); const [pdfDownloadUrl,setPdfDownloadUrl]=useState<string|undefined>(); const [videoUrls,setVideoUrls]=useState<Record<string,string>>({});
 useEffect(()=>{if(!unit)return;let alive=true;const refresh=()=>{const state=readState();setCompleted(state.completed);setPdf(state.unitPdfs[String(unit.id)]);};refresh();window.addEventListener("ai-quest:updated",refresh);const sync=async()=>{const supabase=getSupabaseBrowserClient();if(!supabase)return;const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data}=await supabase.from("lecture_progress").select("lecture_id,completed").eq("user_id",user.id).eq("completed",true);if(alive&&data){const ids=data.map(row=>row.lecture_id);setCompleted(ids);writeState({completed:ids})}};sync();return()=>{alive=false;window.removeEventListener("ai-quest:updated",refresh)}},[unit]);
 useEffect(()=>{let alive=true;const load=async()=>{if(!unit)return;const supabase=getSupabaseBrowserClient();if(supabase){const {data}=await supabase.from("unit_notes").select("title,description,storage_path,published,uploaded_at").eq("unit_id",unit.id).eq("published",true).maybeSingle();if(data?.storage_path){const fileName=data.storage_path.split("/").at(-1)??"unit-notes.pdf";const [view,download]=await Promise.all([supabase.storage.from("course-resources").createSignedUrl(data.storage_path,3600),supabase.storage.from("course-resources").createSignedUrl(data.storage_path,3600,{download:fileName})]);if(alive){setPdf({title:data.title,description:data.description??"",fileName,storagePath:data.storage_path,published:true,uploadedAt:data.uploaded_at});setPdfUrl(view.data?.signedUrl);setPdfDownloadUrl(download.data?.signedUrl);}}else if(alive){setPdfUrl(undefined);setPdfDownloadUrl(undefined)}}else{const item=readState().unitPdfs[String(unit.id)];const resolved=item?.demoFileId?await demoFileUrl(item.demoFileId):item?.url;if(alive){setPdf(item);setPdfUrl(item?.published?resolved:undefined);setPdfDownloadUrl(item?.published?resolved:undefined)}}};load();return()=>{alive=false}},[unit]);
 useEffect(()=>{let alive=true;const load=async()=>{if(!unit)return;for(const lecture of unit.lectures){if(!lecture.videoId)continue;const response=await fetch(`/api/videos/${encodeURIComponent(lecture.id)}`,{cache:"no-store"});if(response.ok){const data=await response.json();if(alive&&data.playbackUrl)setVideoUrls(current=>({...current,[lecture.id]:data.playbackUrl}))}}};load();return()=>{alive=false}},[unit]);
 if(!unit)return <AppShell><div className="card p-10 text-center"><h1 className="title-lg">This unit isn’t here</h1><p className="body-muted mt-2">Please choose one of the seven course units.</p><Link href="/units" className="btn-primary mt-5">Back to units</Link></div></AppShell>;
 const done=unit.lectures.filter(l=>completed.includes(l.id)).length;const percent=unit.lectures.length?Math.round(done/unit.lectures.length*100):0;const toggle=async(id:string)=>{const wasDone=completed.includes(id);const next=wasDone?completed.filter(x=>x!==id):[...completed,id];writeState({completed:next});setCompleted(next);const supabase=getSupabaseBrowserClient();if(supabase){const {data:{user}}=await supabase.auth.getUser();if(user){await supabase.from("lecture_progress").upsert({user_id:user.id,lecture_id:id,completed:!wasDone},{onConflict:"user_id,lecture_id"});if(!wasDone)await supabase.from("learning_activity").insert({user_id:user.id,activity_type:"lecture_completed",entity_type:"lecture",entity_id:id,details:{unit_id:unit.id}})}}};
 return <AppShell><Link href="/units" className="mb-5 inline-flex items-center gap-2 text-[11px] font-bold text-slate-400 hover:text-indigo-600"><ArrowLeft size={14}/>All units</Link><div className="overflow-hidden rounded-[22px] bg-white shadow-sm"><div className="grid md:grid-cols-[1.02fr_.98fr]"><div className="p-6 md:p-8"><span className="badge">UNIT {String(unit.id).padStart(2,"0")}</span><h1 className="title-lg mt-4">{unit.title}</h1><p className="body-muted mt-3 text-sm">{unit.description}</p><div className="mt-5 flex items-center gap-2 text-[11px] text-slate-500"><BookOpen size={15} className="text-indigo-500"/>{unit.lectures.length} lessons<span className="mx-1 text-slate-300">•</span><Clock3 size={14} className="text-indigo-500"/>About 1 hour</div><div className="mt-7"><div className="mb-2 flex justify-between text-[10px]"><b>Unit progress</b><span className="font-bold text-indigo-600">{percent}%</span></div><ProgressBar value={percent}/></div>{unit.lectures.length ? <Link href={`/units/${unit.id}#${unit.lectures.find(l=>!completed.includes(l.id))?.id??unit.lectures[0].id}`} className="btn-primary mt-6"><Play size={14} fill="currentColor"/>Continue learning</Link> : <p className="mt-6 rounded-xl bg-indigo-50/70 p-3 text-[10px] leading-5 text-slate-600">New video lessons will appear here when your course admin publishes them.</p>}</div><div className="relative min-h-[250px] bg-[#f2f4ff] p-4"><CourseImage src={unit.image} alt={`Illustration for ${unit.shortTitle}`} className="!relative h-full min-h-[220px] w-full rounded-2xl object-cover" width={640} height={360} sizes="(max-width:760px) 95vw, 45vw"/></div></div></div>
   <div className="mt-6 grid gap-5 lg:grid-cols-[1.3fr_.7fr]"><div><section className="card p-5 md:p-6"><div className="flex items-center justify-between"><div><span className="eyebrow">WHAT YOU’LL LEARN</span><h2 className="mt-2 text-base font-bold">Learning objectives</h2></div><span className="grid size-9 place-items-center rounded-xl bg-indigo-50 text-indigo-500"><Target size={18}/></span></div><ul className="mt-4 grid gap-3 sm:grid-cols-2">{unit.objectives.map((obj,i)=><li key={obj} className="flex gap-2.5 text-xs leading-5 text-slate-600"><span className="grid size-5 shrink-0 place-items-center rounded-full bg-emerald-50 text-emerald-600"><Check size={12}/></span>{obj}</li>)}</ul><div className="mt-5 border-t border-slate-100 pt-4"><div className="text-[10px] font-bold uppercase tracking-wide text-slate-400">Key topics</div><div className="mt-2 flex flex-wrap gap-2">{unit.topics.map(topic=><span key={topic} className="rounded-full bg-slate-50 px-3 py-1.5 text-[10px] font-semibold text-slate-500">{topic}</span>)}</div></div></section>
    <section className="mt-5"><div className="section-heading"><div><span className="eyebrow">UNIT {String(unit.id).padStart(2,"0")}</span><h2 className="mt-2 text-lg font-bold">Lessons & videos</h2></div><span className="text-[10px] text-slate-400">{done} of {unit.lectures.length} complete</span></div><div className="grid gap-3">{unit.lectures.length ? unit.lectures.map((lecture,index)=>{const isDone=completed.includes(lecture.id);return <article id={lecture.id} key={lecture.id} className="card scroll-mt-24 overflow-hidden"><div className="flex items-start gap-3 p-4"><div className={`grid size-9 shrink-0 place-items-center rounded-xl text-xs font-bold ${isDone?"bg-emerald-50 text-emerald-600":"bg-indigo-50 text-indigo-600"}`}>{isDone?<Check size={17}/>:String(index+1).padStart(2,"0")}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-2"><div><h3 className="text-sm font-bold">{lecture.title}</h3><p className="mt-1 text-[11px] leading-[1.5] text-slate-500">{lecture.description}</p></div><span className="flex shrink-0 items-center gap-1 text-[10px] text-slate-400"><Clock3 size={12}/>{lecture.duration}</span></div><div className="mt-3 flex flex-wrap gap-1.5">{lecture.topics.map(topic=><span key={topic} className="rounded-full bg-slate-50 px-2 py-1 text-[9px] text-slate-500">{topic}</span>)}</div><div className="mt-3">{lecture.videoId&&videoUrls[lecture.id]?<div className="video-frame"><iframe src={videoUrls[lecture.id]} title={lecture.title} allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;" allowFullScreen/></div>:<div className="flex items-center gap-3 rounded-xl bg-[#f7f8fc] p-3"><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-white text-indigo-500"><Video size={17}/></span><span className="flex-1"><b className="block text-[10px]">Lesson video</b><small className="text-[9px] text-slate-400">This video is being prepared for playback. Please check back soon.</small></span><LockKeyhole size={14} className="text-slate-300"/></div>}</div><div className="mt-3 flex justify-end"><button onClick={()=>toggle(lecture.id)} className={isDone?"btn-secondary !py-2 !px-3 text-[10px]":"btn-primary !py-2 !px-3 text-[10px]"}>{isDone?<><Check size={13}/>Completed · undo</>:<>Mark complete <ArrowRight size={13}/></>}</button></div></div></div></article>}) : <div className="card px-6 py-8 text-center"><b className="text-sm font-bold">Your next lesson is on its way</b><p className="body-muted mx-auto mt-2 max-w-sm text-xs">New video lessons appear here after your course admin adds and publishes them.</p></div>}</div></section>
    </div><aside className="space-y-5"><div className="card p-5"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#fff4df] text-amber-500"><FileText size={18}/></span><div><b className="text-sm">Unit notes</b><small className="mt-0.5 block text-[10px] text-slate-400">Your notes for this unit</small></div></div>{pdf?.published&&pdfUrl?<div className="mt-4 rounded-xl bg-slate-50 p-3"><b className="block text-xs">{pdf.title}</b>{pdf.description&&<p className="mt-1 text-[10px] leading-4 text-slate-500">{pdf.description}</p>}<div className="mt-3 flex gap-2"><a className="btn-primary !px-3 !py-2 text-[10px]" href={pdfUrl} target="_blank" rel="noreferrer"><FileText size={13}/>View PDF</a><a className="btn-secondary !px-3 !py-2 text-[10px]" href={pdfDownloadUrl||pdfUrl}><Download size={13}/>Download</a></div></div>:<div className="mt-4 rounded-xl border border-dashed border-slate-200 p-4 text-center"><FileText size={20} className="mx-auto text-slate-300"/><p className="mt-2 text-[10px] leading-4 text-slate-400">Unit notes are being prepared. Check back soon.</p></div>}<small className="mt-3 block text-[9px] text-slate-400">Each unit has its own notes PDF. Only your course admin can add or update it.</small></div>
      <div className="card p-5"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-rose-50 text-rose-500"><CircleHelp size={18}/></span><div><b className="text-sm">Check your understanding</b><small className="mt-0.5 block text-[10px] text-slate-400">Take a quick unit quiz</small></div></div><p className="mt-3 text-[11px] leading-5 text-slate-500">Put the key ideas into practice and get instant feedback on your answers.</p><Link href={`/quizzes?unit=${unit.id}`} className="btn-secondary mt-4 w-full text-[11px]">Go to Unit {unit.id} quiz <ArrowRight size={14}/></Link></div>
      <div className="card p-5"><div className="eyebrow">YOUR PROGRESS</div><div className="mt-3 text-2xl font-bold">{percent}<span className="text-sm text-slate-400">%</span></div><p className="mt-1 text-[10px] text-slate-400">{done} of {unit.lectures.length} lessons complete</p><div className="mt-3"><ProgressBar value={percent}/></div><Link href="/progress" className="mt-4 flex items-center justify-between border-t border-slate-100 pt-3 text-[10px] font-bold text-indigo-600">View all progress<ChevronRight size={14}/></Link></div></aside></div>
   <div className="mt-7 flex justify-between"><Link href={unit.id>1?`/units/${unit.id-1}`:"/units"} className="btn-secondary !py-2.5 text-[11px]"><ArrowLeft size={14}/>{unit.id===1?"All units":"Previous unit"}</Link><Link href={unit.id<7?`/units/${unit.id+1}`:"/progress"} className="btn-secondary !py-2.5 text-[11px]">{unit.id===7?"Course progress":"Next unit"}<ArrowRight size={14}/></Link></div>
 </AppShell>
}
