import Link from "next/link";
import { ArrowRight, BrainCircuit, ChartNoAxesColumnIncreasing, CircleHelp, Play, Sparkles, Star, Video } from "lucide-react";
import { UnitCard } from "@/components/ui";
import { BrandMark } from "@/components/brand-mark";
import { units } from "@/lib/data";

const features = [
  { icon: Video, title: "Learn by video", body: "Clear, focused lessons that make AI ideas easier to understand." },
  { icon: CircleHelp, title: "Practice as you go", body: "Quick quizzes help you check what makes sense and what to revisit." },
  { icon: ChartNoAxesColumnIncreasing, title: "See your progress", body: "Pick up where you left off and celebrate the steps you complete." },
  { icon: Sparkles, title: "Build your AI journey", body: "Grow from curious beginner to confident AI creator, one unit at a time." },
];

export default function HomePage() {
  return <div className="landing">
    <header className="mx-auto flex max-w-[1240px] items-center justify-between px-5 py-5 md:px-10">
      <Link href="/" className="flex items-center gap-3"><BrandMark size={42}/><span><strong className="block text-[17px] tracking-tight">AI Quest</strong><small className="text-[10px] font-semibold text-slate-400">CLASS 10 · ARTIFICIAL INTELLIGENCE</small></span></Link>
      <nav className="hidden items-center gap-8 text-xs font-semibold text-slate-500 md:flex"><a href="#why" className="hover:text-indigo-600">Why AI Quest</a><a href="#units" className="hover:text-indigo-600">Explore units</a><Link href="/papers" className="hover:text-indigo-600">Sample papers</Link></nav>
      <div className="flex items-center gap-2"><Link className="hidden px-3 py-2 text-xs font-bold text-slate-600 sm:block" href="/login">Sign in</Link><Link href="/dashboard" className="btn-primary !py-2.5 !px-3.5 text-xs">Start learning <ArrowRight size={15}/></Link></div>
    </header>
    <section className="hero-bg"><div className="page-wrap hero-grid px-5 py-12 md:px-10 md:py-16">
      <div className="max-w-[560px]"><div className="inline-flex items-center gap-2 rounded-full border border-indigo-100 bg-white px-3 py-1.5 text-[10px] font-bold text-indigo-600 shadow-sm"><Sparkles size={13}/> A smarter way to learn AI</div><h1 className="title-xl mt-5 text-[42px] md:text-[58px]">Learn AI.<br/><span className="text-[#526de6]">Build Skills.</span><br/>Explore the Future.</h1><p className="body-muted mt-5 max-w-md text-sm">A guided, student-friendly journey through Artificial Intelligence for CBSE Class 10. Understand the ideas, try them out, and find your next step.</p><div className="mt-7 flex flex-wrap gap-3"><Link className="btn-primary" href="/dashboard">Start learning <ArrowRight size={16}/></Link><Link className="btn-secondary" href="/units"><BookOpenIcon/>Explore 7 units</Link></div><div className="mt-9 flex flex-wrap items-center gap-x-5 gap-y-2 text-[11px] font-semibold text-slate-500"><span className="flex items-center gap-1.5"><span className="size-1.5 rounded-full bg-emerald-400"/>CBSE-aligned learning</span><span className="flex items-center gap-1.5"><span className="size-1.5 rounded-full bg-indigo-400"/>Made for curious minds</span></div></div>
      <div className="hero-visual hidden md:block"><div className="hero-blob"/><div className="hero-orbit"/><div className="absolute left-[22%] top-[19%] grid size-[210px] place-items-center rounded-full bg-white/90 text-indigo-600 shadow-[0_20px_60px_rgba(61,82,177,.14)]"><BrainCircuit size={93} strokeWidth={1.25}/><span className="absolute bottom-10 rounded-full bg-[#eff1ff] px-3 py-1 text-[10px] font-bold">Your AI learning journey</span></div><div className="floating-card left-[6%] top-[13%] flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-indigo-50 text-indigo-600"><Video size={17}/></span><span className="text-[11px]"><b className="block">Short video lessons</b><small className="text-slate-400">Learn at your own pace</small></span></div><div className="floating-card right-[7%] top-[24%] flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-emerald-50 text-emerald-600"><Star size={17}/></span><span className="text-[11px]"><b className="block">Level up as you go</b><small className="text-slate-400">AI Explorer awaits</small></span></div><div className="floating-card bottom-[12%] left-[24%] w-[240px]"><div className="flex items-center justify-between text-[10px]"><b>Your course progress</b><span className="font-bold text-indigo-600">42%</span></div><div className="progress-track mt-2"><div className="progress-fill" style={{width:"42%"}}/></div><div className="mt-2 text-[9px] text-slate-400">A little learning, every day</div></div></div>
    </div></section>
    <section className="page-wrap grid grid-cols-2 gap-3 px-5 py-8 sm:grid-cols-4 md:px-10"><Metric n="CBSE" label="Aligned learning"/><Metric n="Your pace" label="Flexible study"/><Metric n="Interactive" label="Quizzes"/><Metric n="Sample" label="Papers"/></section>
    <section id="why" className="page-wrap px-5 py-14 md:px-10 md:py-20"><div className="mx-auto max-w-xl text-center"><div className="eyebrow">WHY AI QUEST?</div><h2 className="title-lg mt-3">The future makes more sense when you learn by doing.</h2><p className="body-muted mt-3 text-sm">A calm, clear learning space built around the way students actually learn.</p></div><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{features.map(({icon:Icon,title,body},i)=><div key={title} className="rounded-2xl border border-slate-100 bg-white p-5 shadow-[0_5px_24px_rgba(20,40,90,.035)]"><span className={`grid size-11 place-items-center rounded-[14px] ${i%2?"bg-emerald-50 text-emerald-600":"bg-indigo-50 text-indigo-600"}`}><Icon size={20}/></span><h3 className="mt-4 text-sm font-bold">{title}</h3><p className="body-muted mt-2 text-xs">{body}</p></div>)}</div></section>
    <section id="units" className="bg-[#f7f9fc]"><div className="page-wrap px-5 py-14 md:px-10 md:py-20"><div className="section-heading"><div><div className="eyebrow">YOUR COURSE</div><h2 className="title-lg mt-2">Explore the 7 units</h2><p className="body-muted mt-2">Build understanding one idea at a time.</p></div><Link href="/units" className="btn-secondary hidden sm:inline-flex">View all units <ArrowRight size={15}/></Link></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{units.map(unit=><UnitCard key={unit.id} unit={unit}/>)}</div><div className="mt-5 text-center sm:hidden"><Link href="/units" className="btn-secondary">View all units <ArrowRight size={15}/></Link></div></div></section>
    <section className="page-wrap px-5 py-12 md:px-10 md:py-16"><div className="rounded-3xl bg-[#263d9e] px-6 py-9 text-white md:flex md:items-center md:justify-between md:px-10"><div><span className="text-[10px] font-bold uppercase tracking-[.14em] text-indigo-200">Your next big idea starts here</span><h2 className="mt-2 text-2xl font-bold tracking-tight md:text-3xl">Ready to explore AI?</h2><p className="mt-2 max-w-lg text-xs leading-5 text-indigo-100">Take your first step. Your learning journey is waiting.</p></div><Link href="/dashboard" className="mt-5 inline-flex items-center gap-2 rounded-xl bg-white px-4 py-3 text-xs font-bold text-indigo-700 md:mt-0">Start your journey <ArrowRight size={16}/></Link></div></section>
    <footer className="border-t border-slate-100 px-5 py-6 text-center text-[10px] text-slate-400">Made with love by Aivora</footer>
  </div>;
}

function Metric({n,label}:{n:string;label:string}) { return <div className="rounded-2xl border border-slate-100 bg-white p-4 text-center"><b className="block text-lg text-slate-800">{n}</b><span className="mt-1 block text-[10px] font-semibold text-slate-400">{label}</span></div>; }
function BookOpenIcon() { return <span aria-hidden="true">✦</span>; }
