"use client";

import { FormEvent, useEffect, useState } from "react";
import { CheckCircle2, GraduationCap, LogOut, School, UserRound } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { PageHeading, ProgressBar } from "@/components/ui";
import { getLearningStats, readState, writeState } from "@/lib/store";
import { useCourseUnits } from "@/lib/hooks";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";

export default function ProfilePage(){
 const units=useCourseUnits();
 const [profile,setProfile]=useState(readState().profile);const [stats,setStats]=useState(getLearningStats(units));const [saved,setSaved]=useState(false);
 useEffect(()=>{let alive=true;setProfile(readState().profile);setStats(getLearningStats(units));const sync=async()=>{const supabase=getSupabaseBrowserClient();if(!supabase)return;const {data:{user}}=await supabase.auth.getUser();if(!user)return;const [profile,progress,quiz]=await Promise.all([supabase.from("profiles").select("full_name,roll_number,class_name,school").eq("id",user.id).maybeSingle(),supabase.from("lecture_progress").select("lecture_id").eq("user_id",user.id).eq("completed",true),supabase.from("quiz_attempts").select("id,unit_id,score_percent,correct_answers,total_questions,created_at").eq("user_id",user.id).order("created_at",{ascending:false})]);if(!alive)return;const attempts=(quiz.data??[]).map(row=>({id:row.id,unitId:row.unit_id,score:row.score_percent,correct:row.correct_answers,total:row.total_questions,date:row.created_at}));writeState({profile:profile.data?{name:profile.data.full_name||"Student",roll:profile.data.roll_number||"",className:profile.data.class_name||"10",school:profile.data.school||""}:readState().profile,completed:(progress.data??[]).map(row=>row.lecture_id),attempts,quizScores:attempts.map(row=>row.score)});setProfile(readState().profile);setStats(getLearningStats(units))};sync();return()=>{alive=false}},[units]);
 const update=(key:keyof typeof profile,value:string)=>setProfile(current=>({...current,[key]:value}));
 const submit=async(event:FormEvent)=>{event.preventDefault();writeState({profile});const supabase=getSupabaseBrowserClient();if(supabase){const {data:{user}}=await supabase.auth.getUser();if(user)await supabase.from("profiles").update({full_name:profile.name,roll_number:profile.roll,class_name:profile.className,school:profile.school}).eq("id",user.id)}setSaved(true);setTimeout(()=>setSaved(false),2500)};
 const signOut=async()=>{await getSupabaseBrowserClient()?.auth.signOut();window.location.href="/"};
 const total=units.reduce((count,unit)=>count+unit.lectures.length,0);
 return <AppShell><PageHeading eyebrow="YOUR ACCOUNT" title="Student profile" text="Keep your learning details up to date." action={<button onClick={signOut} className="btn-secondary text-[10px]"><LogOut size={14}/>Sign out</button>}/><section className="card mb-5 flex items-center gap-4 p-5"><span className="grid size-16 place-items-center rounded-[20px] bg-indigo-50 text-2xl font-bold text-indigo-600">{profile.name.slice(0,1).toUpperCase()}</span><div className="flex-1"><h2 className="text-lg font-bold">{profile.name}</h2><p className="mt-1 text-[11px] text-slate-400">Class {profile.className} · {profile.roll||"Student"}</p><span className="badge mt-2"><GraduationCap size={12} className="mr-1"/>Class 10 Artificial Intelligence</span></div><div className="hidden min-w-32 sm:block"><div className="flex justify-between text-[9px]"><span className="text-slate-400">Course progress</span><b>{stats.overall}%</b></div><div className="mt-2"><ProgressBar value={stats.overall}/></div></div></section>
 <div className="grid items-start gap-5 lg:grid-cols-[1fr_320px]"><form onSubmit={submit} className="card p-5 md:p-6"><div className="flex items-center gap-2"><span className="grid size-8 place-items-center rounded-xl bg-indigo-50 text-indigo-500"><UserRound size={16}/></span><h2 className="text-sm font-bold">Student details</h2></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><div><label className="label" htmlFor="fullname">Full name</label><input id="fullname" className="field" required value={profile.name} onChange={e=>update("name",e.target.value)}/></div><div><label className="label" htmlFor="roll">Roll number</label><input id="roll" className="field" value={profile.roll} onChange={e=>update("roll",e.target.value)}/></div><div><label className="label" htmlFor="class">Class</label><input id="class" className="field" value={profile.className} onChange={e=>update("className",e.target.value)}/></div><div><label className="label" htmlFor="school">School</label><input id="school" className="field" value={profile.school} onChange={e=>update("school",e.target.value)}/></div></div><button type="submit" className="btn-primary mt-5 text-[11px]">Save details</button>{saved&&<div role="status" className="ml-3 inline-flex items-center gap-1 text-[10px] font-semibold text-emerald-700"><CheckCircle2 size={14}/>Saved</div>}<p className="mt-3 text-[9px] text-slate-400">Account email and password are managed through secure sign-in.</p></form>
 <aside className="card p-5"><div className="flex items-center gap-2"><span className="grid size-8 place-items-center rounded-xl bg-emerald-50 text-emerald-600"><School size={16}/></span><h2 className="text-sm font-bold">Learning snapshot</h2></div><div className="mt-5 divide-y divide-slate-100">{[{label:"Overall progress",value:`${stats.overall}%`},{label:"Units completed",value:`${stats.doneUnits} / 7`},{label:"Lessons completed",value:`${stats.completed} / ${total}`},{label:"Quiz average",value:stats.quizAverage?`${stats.quizAverage}%`:"—"}].map(item=><div key={item.label} className="flex justify-between py-3 first:pt-0 last:pb-0"><span className="text-[10px] text-slate-500">{item.label}</span><b className="text-[10px]">{item.value}</b></div>)}</div><div className="mt-5 rounded-xl bg-slate-50 p-3 text-[10px] text-slate-500">Currently exploring <b className="text-slate-700">{units[Math.min(6,stats.doneUnits)]?.shortTitle}</b></div></aside></div></AppShell>
}
