"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowRight, Check, CircleHelp, Clock3, Sparkles, Trophy } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { PageHeading, ProgressBar } from "@/components/ui";
import { levelNames } from "@/lib/data";
import { getLearningStats, readState, writeState } from "@/lib/store";
import { useCourseUnits } from "@/lib/hooks";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";

export default function ProgressPage(){
 const units=useCourseUnits();
 const [stats,setStats]=useState(getLearningStats(units));const [attempts,setAttempts]=useState(readState().attempts??[]);
 useEffect(()=>{let alive=true;const update=()=>{setStats(getLearningStats(units));setAttempts(readState().attempts??[])};window.addEventListener("ai-quest:updated",update);const sync=async()=>{const supabase=getSupabaseBrowserClient();if(!supabase)return;const {data:{user}}=await supabase.auth.getUser();if(!user)return;const [progress,quiz]=await Promise.all([supabase.from("lecture_progress").select("lecture_id").eq("user_id",user.id).eq("completed",true),supabase.from("quiz_attempts").select("id,unit_id,score_percent,correct_answers,total_questions,created_at").eq("user_id",user.id).order("created_at",{ascending:false})]);if(!alive)return;const attempts=(quiz.data??[]).map(row=>({id:row.id,unitId:row.unit_id,score:row.score_percent,correct:row.correct_answers,total:row.total_questions,date:row.created_at}));writeState({completed:(progress.data??[]).map(row=>row.lecture_id),attempts,quizScores:attempts.map(row=>row.score)});update()};sync();return()=>{alive=false;window.removeEventListener("ai-quest:updated",update)}},[units]);
 const level=Math.min(4,Math.floor(stats.overall/20));const unitPct=(id:number)=>{const unit=units.find(u=>u.id===id);return unit?.lectures.length?Math.round(unit.lectures.filter(l=>stats.completedIds.includes(l.id)).length/unit.lectures.length*100):0};const total=units.reduce((count,unit)=>count+unit.lectures.length,0);
 return <AppShell><PageHeading eyebrow="YOUR AI LEARNING JOURNEY" title="Progress & milestones" text="See how far you’ve come and choose a good next step."/><section className="grid gap-4 md:grid-cols-[1fr_1fr]"><div className="rounded-[22px] bg-gradient-to-br from-[#405ce0] to-[#767ee9] p-6 text-white"><div className="flex items-start justify-between"><div><span className="text-[10px] font-bold tracking-wider text-indigo-100">OVERALL COURSE PROGRESS</span><div className="mt-3 text-[42px] font-bold tracking-tight">{stats.overall}<span className="text-lg text-indigo-200">%</span></div></div><div className="grid size-12 place-items-center rounded-2xl bg-white/15"><Trophy size={22}/></div></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/20"><div className="h-full rounded-full bg-emerald-300" style={{width:`${stats.overall}%`}}/></div><p className="mt-4 text-[10px] text-indigo-100">{stats.completed} of {total} lessons completed</p></div><div className="card p-6"><span className="badge"><Sparkles size={12} className="mr-1"/>CURRENT LEVEL</span><h2 className="mt-3 text-xl font-bold">{levelNames[level]}</h2><p className="mt-1 text-[11px] text-slate-500">{level===4?"You’ve reached the final milestone!":`${100-(stats.overall%20||0)}% of the way to ${levelNames[Math.min(4,level+1)]}`}</p><div className="mt-5 grid grid-cols-5 gap-1">{levelNames.map((name,i)=><div key={name} className="text-center"><div className={`mx-auto grid size-8 place-items-center rounded-full text-[10px] ${i<=level?"bg-indigo-600 text-white":"bg-slate-100 text-slate-400"}`}>{i<level?<Check size={14}/>:i+1}</div><small className={`mt-1 block text-[8px] leading-3 ${i<=level?"font-bold text-indigo-700":"text-slate-400"}`}>{name}</small></div>)}</div></div></section>
  <section className="mt-7"><div className="section-heading"><div><div className="eyebrow">YOUR COURSE MAP</div><h2 className="mt-2 text-lg font-bold">Unit completion</h2></div><Link href="/units" className="flex items-center gap-1 text-[10px] font-bold text-indigo-600">Keep learning <ArrowRight size={13}/></Link></div><div className="grid gap-3">{units.map((unit,i)=>{const pct=unitPct(unit.id);const done=unit.lectures.filter(l=>stats.completedIds.includes(l.id)).length;return <Link href={`/units/${unit.id}`} key={unit.id} className="card flex items-center gap-3 p-4 transition hover:shadow-md"><img src={unit.image} alt="" className="size-12 rounded-xl object-cover"/><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-3"><div className="truncate text-xs font-bold">{unit.shortTitle}</div><div className="shrink-0 text-[10px] font-semibold text-slate-500">{pct}%</div></div><div className="mt-2"><ProgressBar value={pct}/></div><small className="mt-1.5 block text-[9px] text-slate-400">{done} of {unit.lectures.length} lessons</small></div><span className={`hidden size-8 place-items-center rounded-full sm:grid ${pct===100?"bg-emerald-50 text-emerald-600":"bg-slate-50 text-slate-300"}`}>{pct===100?<Check size={15}/>:<span className="text-[9px]">{i+1}</span>}</span></Link>})}</div></section>
  <section className="mt-7 grid gap-5 md:grid-cols-2"><div className="card p-5"><div className="flex items-center gap-2"><span className="grid size-8 place-items-center rounded-xl bg-rose-50 text-rose-500"><CircleHelp size={16}/></span><h2 className="text-sm font-bold">Quiz performance</h2></div><div className="mt-5 flex items-end justify-between"><span className="text-3xl font-bold">{stats.quizAverage?`${stats.quizAverage}%`:"—"}</span><span className="text-[10px] text-slate-400">{attempts.length} {attempts.length===1?"attempt":"attempts"}</span></div><div className="mt-3"><ProgressBar value={stats.quizAverage}/></div><p className="mt-3 text-[10px] text-slate-400">Average score across your submitted quizzes.</p></div><div className="card p-5"><div className="flex items-center gap-2"><span className="grid size-8 place-items-center rounded-xl bg-amber-50 text-amber-500"><Clock3 size={16}/></span><h2 className="text-sm font-bold">Learning activity</h2></div>{stats.completedIds.length?<div className="mt-4 space-y-3">{[...stats.completedIds].slice(-4).reverse().map(id=>{const unit=units.find(u=>u.lectures.some(l=>l.id===id))!;const lesson=unit.lectures.find(l=>l.id===id)!;return <div key={id} className="flex items-center gap-3"><span className="grid size-7 place-items-center rounded-lg bg-emerald-50 text-emerald-600"><Check size={14}/></span><div className="flex-1"><b className="block text-[10px]">Completed {lesson.title}</b><small className="text-[9px] text-slate-400">Unit {unit.id} · Lesson</small></div><small className="text-[9px] text-slate-400">Done</small></div>})}</div>:<p className="mt-4 rounded-xl bg-slate-50 p-4 text-[10px] leading-5 text-slate-500">Your learning activity will build as you complete lessons and quizzes.</p>}</div></section>
 </AppShell>
}
