export type Lecture = { id: string; title: string; description: string; duration: string; topics: string[]; videoId?: string; completed?: boolean; published?: boolean };
export type Unit = { id: number; title: string; shortTitle: string; description: string; color: string; image: string; objectives: string[]; topics: string[]; lectures: Lecture[]; published?: boolean };

export const units: Unit[] = [
  { id: 1, title: "Revisiting AI Project Cycle & Ethical Frameworks for AI", shortTitle: "AI Project Cycle & Ethics", description: "Plan thoughtful AI solutions, revisit the project cycle and explore the values that make AI responsible.", color: "#7164db", image: "/images/unit-1.svg", objectives: ["Revisit the stages of the AI Project Cycle", "Identify ethical concerns in AI systems", "Apply responsible AI principles to real scenarios"], topics: ["AI Project Cycle", "Problem scoping", "Responsible AI", "Ethical frameworks"], lectures: [{ id: "1-1", title: "The AI Project Cycle, Revisited", description: "Connect the five stages of an AI project to a real-world challenge.", duration: "12 min", topics: ["Problem scoping", "Data acquisition"] }, { id: "1-2", title: "From Data to a Model", description: "See how data exploration and modelling fit into the cycle.", duration: "16 min", topics: ["Data exploration", "Modelling"] }, { id: "1-3", title: "Ethics in Artificial Intelligence", description: "Explore fairness, privacy, transparency and accountability.", duration: "18 min", topics: ["Fairness", "Privacy", "Transparency"] }, { id: "1-4", title: "Responsible AI in Practice", description: "Use an ethical framework to discuss everyday AI scenarios.", duration: "14 min", topics: ["Ethical frameworks", "Case study"] }] },
  { id: 2, title: "Advanced Concepts of Modeling in AI", shortTitle: "Advanced AI Modelling", description: "Go deeper into machine learning models, their learning patterns and how they make predictions.", color: "#328d9b", image: "/images/unit-2.svg", objectives: ["Compare supervised and unsupervised learning", "Explain how models learn from data", "Choose a modelling approach for a problem"], topics: ["Supervised learning", "Unsupervised learning", "Neural networks", "Training"], lectures: [{ id: "2-1", title: "How AI Models Learn", description: "A practical introduction to model training and patterns.", duration: "15 min", topics: ["Training data", "Patterns"] }, { id: "2-2", title: "Supervised Learning", description: "Learn from labelled examples through classification and regression.", duration: "18 min", topics: ["Classification", "Regression"] }, { id: "2-3", title: "Unsupervised Learning", description: "Discover how a model can find groups and structure without labels.", duration: "13 min", topics: ["Clustering", "Patterns"] }, { id: "2-4", title: "Neural Networks: The Basics", description: "Meet layers, weights and activation in an approachable way.", duration: "20 min", topics: ["Neural network", "Layers"] }] },
  { id: 3, title: "Evaluating Models", shortTitle: "Evaluating Models", description: "Measure how well an AI model performs and understand the story behind its results.", color: "#e19848", image: "/images/unit-3.svg", objectives: ["Explain train-test split", "Read a confusion matrix", "Calculate accuracy, precision, recall and F1 score"], topics: ["Train-test split", "Confusion matrix", "Accuracy", "Precision & recall"], lectures: [{ id: "3-1", title: "Why Evaluate a Model?", description: "Understand the need to check how a model performs on new data.", duration: "11 min", topics: ["Evaluation", "Generalisation"] }, { id: "3-2", title: "Train-Test Split", description: "Keep an honest set of examples for testing model performance.", duration: "13 min", topics: ["Training data", "Testing data"] }, { id: "3-3", title: "Confusion Matrix", description: "Read true and false predictions in a simple grid.", duration: "15 min", topics: ["True positive", "False positive"] }, { id: "3-4", title: "Accuracy, Precision & Recall", description: "Select the right metric for the question you need to answer.", duration: "20 min", topics: ["Accuracy", "Precision", "Recall", "F1 score"] }] },
  { id: 4, title: "Statistical Data", shortTitle: "Statistical Data", description: "Summarise, compare and communicate data with statistical measures and clear visualisations.", color: "#a16bc0", image: "/images/unit-4.svg", objectives: ["Describe data using statistical measures", "Interpret charts and distributions", "Recognise how statistics informs AI"], topics: ["Mean, median & mode", "Data distribution", "Visualisation", "Outliers"], lectures: [{ id: "4-1", title: "Data and Its Distribution", description: "See what the shape and spread of a dataset can tell you.", duration: "14 min", topics: ["Distribution", "Spread"] }, { id: "4-2", title: "Mean, Median and Mode", description: "Choose a useful measure of central tendency.", duration: "15 min", topics: ["Mean", "Median", "Mode"] }, { id: "4-3", title: "Reading Graphs and Charts", description: "Tell a clear, accurate story with visual data.", duration: "12 min", topics: ["Charts", "Visualisation"] }, { id: "4-4", title: "Outliers and Fair Data", description: "Notice unusual values and understand their impact.", duration: "13 min", topics: ["Outliers", "Data quality"] }] },
  { id: 5, title: "Computer Vision", shortTitle: "Computer Vision", description: "Explore how machines interpret images and video, from pixels to useful predictions.", color: "#4d9b81", image: "/images/unit-5.svg", objectives: ["Explain how images become data", "Compare image classification and object detection", "Discuss real-world computer vision applications"], topics: ["Pixels", "Image classification", "Object detection", "Applications"], lectures: [{ id: "5-1", title: "How a Computer Sees", description: "Turn an image into pixels and numerical data.", duration: "12 min", topics: ["Pixels", "Image data"] }, { id: "5-2", title: "Image Classification", description: "Understand how a model labels an image.", duration: "15 min", topics: ["Classification", "Features"] }, { id: "5-3", title: "Object Detection", description: "Find and locate objects in a picture.", duration: "16 min", topics: ["Detection", "Bounding boxes"] }, { id: "5-4", title: "Vision Around Us", description: "Explore useful and responsible computer vision applications.", duration: "13 min", topics: ["Applications", "Ethics"] }] },
  { id: 6, title: "Natural Language Processing", shortTitle: "Natural Language Processing", description: "Discover how AI works with human language in chatbots, translation and text analysis.", color: "#d66c89", image: "/images/unit-6.svg", objectives: ["Describe common NLP tasks", "Explain how text is prepared for models", "Evaluate chatbot and language applications"], topics: ["Text processing", "Chatbots", "Sentiment analysis", "Language models"], lectures: [{ id: "6-1", title: "What Is NLP?", description: "Meet the AI field that works with human language.", duration: "12 min", topics: ["Language", "NLP tasks"] }, { id: "6-2", title: "Preparing Text for AI", description: "Explore tokens and simple text preprocessing.", duration: "14 min", topics: ["Tokens", "Preprocessing"] }, { id: "6-3", title: "Chatbots and Intent", description: "Learn how a chatbot can identify what someone needs.", duration: "17 min", topics: ["Chatbots", "Intent"] }, { id: "6-4", title: "Sentiment Analysis", description: "Use examples to classify the tone of a sentence.", duration: "15 min", topics: ["Sentiment", "Classification"] }] },
  { id: 7, title: "Advanced Python", shortTitle: "Advanced Python", description: "Strengthen your Python foundations with functions, data structures and AI-focused practice.", color: "#4d82ca", image: "/images/unit-7.svg", objectives: ["Write reusable Python functions", "Work confidently with lists and dictionaries", "Use Python to explore simple data"], topics: ["Functions", "Lists & dictionaries", "Libraries", "Data practice"], lectures: [{ id: "7-1", title: "Functions and Reusable Code", description: "Organise code into clear, reusable functions.", duration: "16 min", topics: ["Functions", "Parameters"] }, { id: "7-2", title: "Lists and Dictionaries", description: "Store and work with useful collections of data.", duration: "18 min", topics: ["Lists", "Dictionaries"] }, { id: "7-3", title: "Working with Data", description: "Use familiar Python patterns to explore small datasets.", duration: "20 min", topics: ["Data", "Loops"] }, { id: "7-4", title: "Python for AI: Mini Project", description: "Put your skills together in a compact AI-inspired activity.", duration: "24 min", topics: ["Mini project", "Practice"] }] },
];

export const announcements = [
  { id: "welcome", title: "Welcome to your AI learning journey", text: "Explore the seven course units at your own pace. Your progress is saved as you learn.", date: "Today", icon: "spark" },
  { id: "study", title: "A little practice goes a long way", text: "Try a short quiz after each unit to check what you remember.", date: "This week", icon: "book" },
];

export const levelNames = ["AI Starter", "AI Explorer", "Model Builder", "AI Analyst", "AI Creator"];
export const totalLectures = units.reduce((sum, unit) => sum + unit.lectures.length, 0);
