"use client";

import { useEffect, useMemo, useState } from "react";
import { Download, FileText, Search, SlidersHorizontal } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { EmptyState, PageHeading } from "@/components/ui";
import { readState, type PaperRecord } from "@/lib/store";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";
import { demoFileUrl } from "@/lib/demo-files";

export default function PapersPage(){
 const [papers,setPapers]=useState<PaperRecord[]>([]);const [query,setQuery]=useState("");const [kind,setKind]=useState("All types");const [session,setSession]=useState("All sessions");
 useEffect(()=>{let alive=true;const refresh=async()=>{const local=readState().papers.filter(p=>p.published);const resolved=await Promise.all(local.map(async p=>p.demoFileId?{...p,url:await demoFileUrl(p.demoFileId)}:p));if(alive)setPapers(resolved)};refresh();window.addEventListener("ai-quest:updated",refresh);const load=async()=>{const supabase=getSupabaseBrowserClient();if(!supabase)return;const {data}=await supabase.from("sample_papers").select("id,title,description,session,paper_type,storage_path,published,created_at").eq("published",true).order("created_at",{ascending:false});if(alive&&data){const rows=await Promise.all(data.map(async item=>{const [view,download]=await Promise.all([supabase.storage.from("course-resources").createSignedUrl(item.storage_path,3600),supabase.storage.from("course-resources").createSignedUrl(item.storage_path,3600,{download:item.storage_path.split("/").at(-1)})]);return {id:item.id,title:item.title,description:item.description??"",session:item.session,type:item.paper_type,storagePath:item.storage_path,url:view.data?.signedUrl,downloadUrl:download.data?.signedUrl,fileName:item.storage_path.split("/").at(-1),published:item.published,createdAt:item.created_at}}));setPapers(rows)}};load();return()=>{alive=false;window.removeEventListener("ai-quest:updated",refresh)}},[]);
 const filtered=useMemo(()=>papers.filter(p=>(!query||`${p.title} ${p.session} ${p.type} ${p.description}`.toLowerCase().includes(query.toLowerCase()))&&(kind==="All types"||p.type===kind)&&(session==="All sessions"||p.session===session)),[papers,query,kind,session]);const kinds=["All types",...Array.from(new Set(papers.map(p=>p.type)))];const sessions=["All sessions",...Array.from(new Set(papers.map(p=>p.session)))];
 return <AppShell><PageHeading eyebrow="PREPARE WITH CONFIDENCE" title="CBSE Sample Papers" text="Practice with papers shared by your course team. New resources will appear here when they are published." action={<span className="badge"><FileText size={12} className="mr-1"/>Course resources</span>}/>
  <div className="card mb-5 p-4"><div className="grid gap-3 md:grid-cols-[1fr_190px_190px]"><div className="relative"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input className="field !pl-9 text-xs" aria-label="Search sample papers" placeholder="Search papers, sessions..." value={query} onChange={e=>setQuery(e.target.value)}/></div><label className="relative"><SlidersHorizontal size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><select className="field !pl-9 text-xs" aria-label="Filter by type" value={kind} onChange={e=>setKind(e.target.value)}>{kinds.map(v=><option key={v}>{v}</option>)}</select></label><select className="field text-xs" aria-label="Filter by session" value={session} onChange={e=>setSession(e.target.value)}>{sessions.map(v=><option key={v}>{v}</option>)}</select></div><div className="mt-3 flex justify-between text-[10px] text-slate-400"><span>{filtered.length} published {filtered.length===1?"paper":"papers"}</span><span>PDF resources · Read or download</span></div></div>
  {filtered.length?<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map((paper,i)=><article key={paper.id} className="card overflow-hidden"><div className={`flex h-[92px] items-center justify-center ${i%3===0?"bg-[#eef1ff]":i%3===1?"bg-[#e9f7f3]":"bg-[#fff2e5]"}`}><span className="grid size-12 place-items-center rounded-2xl bg-white text-indigo-500 shadow-sm"><FileText size={23}/></span></div><div className="p-4"><div className="flex items-center justify-between"><span className="badge">{paper.type}</span><span className="text-[9px] text-slate-400">{paper.session}</span></div><h2 className="mt-3 text-sm font-bold">{paper.title}</h2><p className="mt-1.5 min-h-9 text-[10px] leading-[1.6] text-slate-500">{paper.description||"CBSE Artificial Intelligence practice resource."}</p><div className="mt-4 grid grid-cols-2 gap-2"><a href={paper.url||"#"} target="_blank" rel="noreferrer" className="btn-secondary !py-2.5 text-[10px]" aria-disabled={!paper.url}><FileText size={13}/>View PDF</a><a href={paper.downloadUrl||paper.url||"#"} className="btn-primary !py-2.5 text-[10px]" aria-disabled={!paper.url}><Download size={13}/>Download</a></div></div></article>)}</div>:<EmptyState icon="file" title={papers.length?"No papers match those filters":"No sample papers yet"} text={papers.length?"Try another search term or clear one of your filters.":"Your course team will publish CBSE practice papers here. When a paper is available, you can view or download its PDF."} action={papers.length?<button onClick={()=>{setQuery("");setKind("All types");setSession("All sessions")}} className="btn-secondary text-[10px]">Clear filters</button>:undefined}/>}
 </AppShell>
}
