-- AI Quest · scalable course schema, security policies, student RPCs and Class 10 AI seed.
create extension if not exists pgcrypto;

create table if not exists public.classes (
  id bigint generated by default as identity primary key,
  grade smallint not null unique,
  name text not null
);

create table if not exists public.subjects (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  slug text not null unique
);

create table if not exists public.courses (
  id uuid primary key default gen_random_uuid(),
  class_id bigint not null references public.classes(id) on delete restrict,
  subject_id uuid not null references public.subjects(id) on delete restrict,
  title text not null,
  slug text not null unique,
  description text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (class_id, subject_id)
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  roll_number text,
  class_name text not null default '10',
  school text not null default '',
  role text not null default 'student' check (role in ('student','admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin') $$;

create or replace function public.prevent_profile_role_escalation()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  if new.role is distinct from old.role and not public.is_admin() then
    raise exception 'Only an administrator can change account roles';
  end if;
  return new;
end;
$$;
drop trigger if exists profiles_prevent_role_escalation on public.profiles;
create trigger profiles_prevent_role_escalation before update on public.profiles
for each row execute function public.prevent_profile_role_escalation();

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, roll_number, class_name, school, role)
  values (new.id,
    coalesce(new.raw_user_meta_data->>'full_name',''),
    nullif(new.raw_user_meta_data->>'roll_number',''),
    coalesce(new.raw_user_meta_data->>'class_name','10'),
    coalesce(new.raw_user_meta_data->>'school',''),
    'student')
  on conflict (id) do nothing;
  return new;
end;
$$;
drop trigger if exists on_auth_user_created_ai_quest on auth.users;
create trigger on_auth_user_created_ai_quest after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.touch_updated_at()
returns trigger language plpgsql set search_path = public
as $$ begin new.updated_at = now(); return new; end; $$;
drop trigger if exists profiles_touch_updated_at on public.profiles;
create trigger profiles_touch_updated_at before update on public.profiles
for each row execute function public.touch_updated_at();

create table if not exists public.units (
  id integer generated by default as identity primary key,
  course_id uuid not null references public.courses(id) on delete cascade,
  unit_number integer not null,
  title text not null,
  short_title text not null,
  description text not null default '',
  color text not null default '#3f62e8',
  hero_image_url text not null default '',
  objectives text[] not null default '{}',
  topics text[] not null default '{}',
  position integer not null default 0,
  published boolean not null default false,
  created_at timestamptz not null default now(),
  unique (course_id, unit_number),
  unique (course_id, position)
);

create table if not exists public.lectures (
  id text primary key,
  unit_id integer not null references public.units(id) on delete cascade,
  title text not null,
  description text not null default '',
  duration text not null default '',
  topics text[] not null default '{}',
  video_provider text check (video_provider is null or video_provider in ('cloudflare')),
  video_id text,
  position integer not null default 0,
  published boolean not null default false,
  created_at timestamptz not null default now(),
  unique (unit_id, position)
);

create table if not exists public.unit_notes (
  id uuid primary key default gen_random_uuid(),
  unit_id integer not null unique references public.units(id) on delete cascade,
  title text not null,
  description text not null default '',
  storage_path text not null,
  published boolean not null default false,
  uploaded_by uuid references public.profiles(id) on delete set null,
  uploaded_at timestamptz not null default now()
);

create table if not exists public.quizzes (
  id uuid primary key default gen_random_uuid(),
  unit_id integer not null references public.units(id) on delete cascade,
  title text not null,
  description text not null default '',
  published boolean not null default false,
  created_at timestamptz not null default now(),
  unique (unit_id, title)
);

create table if not exists public.quiz_questions (
  id uuid primary key default gen_random_uuid(),
  quiz_id uuid not null references public.quizzes(id) on delete cascade,
  question_text text not null,
  question_type text not null check (question_type in ('multiple_choice','true_or_false','scenario')),
  options jsonb not null check (jsonb_typeof(options) = 'array'),
  correct_option integer not null check (correct_option >= 0),
  explanation text not null default '',
  position integer not null default 0,
  published boolean not null default false,
  created_at timestamptz not null default now(),
  unique (quiz_id, position)
);

create table if not exists public.quiz_attempts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  quiz_id uuid references public.quizzes(id) on delete set null,
  unit_id integer not null references public.units(id) on delete cascade,
  score_percent smallint not null check (score_percent between 0 and 100),
  correct_answers integer not null,
  total_questions integer not null,
  answers jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.sample_papers (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text not null default '',
  session text not null,
  paper_type text not null default 'Sample Paper',
  storage_path text not null,
  published boolean not null default false,
  uploaded_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.announcements (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  text text not null,
  published boolean not null default false,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.suggestions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  subject text not null,
  message text not null,
  reviewed boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.lecture_progress (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  lecture_id text not null references public.lectures(id) on delete cascade,
  completed boolean not null default false,
  video_seconds integer not null default 0 check (video_seconds >= 0),
  duration_seconds integer not null default 0 check (duration_seconds >= 0),
  updated_at timestamptz not null default now(),
  unique (user_id, lecture_id)
);

create table if not exists public.learning_activity (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  activity_type text not null,
  entity_type text,
  entity_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists units_course_position_idx on public.units(course_id, position);
create index if not exists lectures_unit_position_idx on public.lectures(unit_id, position);
create index if not exists quiz_attempts_user_created_idx on public.quiz_attempts(user_id, created_at desc);
create index if not exists suggestions_created_idx on public.suggestions(created_at desc);
create index if not exists learning_activity_user_created_idx on public.learning_activity(user_id, created_at desc);

-- Private files: students get signed URLs only for content whose metadata is published.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('course-resources','course-resources',false,52428800,array['application/pdf','image/png','image/jpeg','image/webp','image/svg+xml'])
on conflict (id) do update set public=false, file_size_limit=52428800, allowed_mime_types=excluded.allowed_mime_types;

-- Course scaffold: exactly seven current units, while classes/subjects/courses support future growth.
insert into public.classes (id,grade,name) values (10,10,'Class 10') on conflict (id) do nothing;
select setval(pg_get_serial_sequence('public.classes','id'), greatest((select max(id) from public.classes),10));
insert into public.subjects (id,name,slug) values ('00000000-0000-4000-8000-000000000020','Artificial Intelligence','artificial-intelligence') on conflict (id) do nothing;
insert into public.courses (id,class_id,subject_id,title,slug,description,active) values ('00000000-0000-4000-8000-000000000010',10,'00000000-0000-4000-8000-000000000020','Class 10 Artificial Intelligence','class-10-artificial-intelligence','CBSE-aligned Artificial Intelligence learning course.',true) on conflict (id) do nothing;

insert into public.units (id,course_id,unit_number,title,short_title,description,color,hero_image_url,objectives,topics,position,published) values
(1,'00000000-0000-4000-8000-000000000010',1,'Revisiting AI Project Cycle & Ethical Frameworks for AI','AI Project Cycle & Ethics','Plan thoughtful AI solutions, revisit the project cycle and explore the values that make AI responsible.','#7164db','/images/unit-1.svg',array['Revisit the stages of the AI Project Cycle','Identify ethical concerns in AI systems','Apply responsible AI principles to real scenarios'],array['AI Project Cycle','Problem scoping','Responsible AI','Ethical frameworks'],1,true),
(2,'00000000-0000-4000-8000-000000000010',2,'Advanced Concepts of Modeling in AI','Advanced AI Modelling','Go deeper into machine learning models, their learning patterns and how they make predictions.','#328d9b','/images/unit-2.svg',array['Compare supervised and unsupervised learning','Explain how models learn from data','Choose a modelling approach for a problem'],array['Supervised learning','Unsupervised learning','Neural networks','Training'],2,true),
(3,'00000000-0000-4000-8000-000000000010',3,'Evaluating Models','Evaluating Models','Measure how well an AI model performs and understand the story behind its results.','#e19848','/images/unit-3.svg',array['Explain train-test split','Read a confusion matrix','Calculate accuracy, precision, recall and F1 score'],array['Train-test split','Confusion matrix','Accuracy','Precision & recall'],3,true),
(4,'00000000-0000-4000-8000-000000000010',4,'Statistical Data','Statistical Data','Summarise, compare and communicate data with statistical measures and clear visualisations.','#a16bc0','/images/unit-4.svg',array['Describe data using statistical measures','Interpret charts and distributions','Recognise how statistics informs AI'],array['Mean, median & mode','Data distribution','Visualisation','Outliers'],4,true),
(5,'00000000-0000-4000-8000-000000000010',5,'Computer Vision','Computer Vision','Explore how machines interpret images and video, from pixels to useful predictions.','#4d9b81','/images/unit-5.svg',array['Explain how images become data','Compare image classification and object detection','Discuss real-world computer vision applications'],array['Pixels','Image classification','Object detection','Applications'],5,true),
(6,'00000000-0000-4000-8000-000000000010',6,'Natural Language Processing','Natural Language Processing','Discover how AI works with human language in chatbots, translation and text analysis.','#d66c89','/images/unit-6.svg',array['Describe common NLP tasks','Explain how text is prepared for models','Evaluate chatbot and language applications'],array['Text processing','Chatbots','Sentiment analysis','Language models'],6,true),
(7,'00000000-0000-4000-8000-000000000010',7,'Advanced Python','Advanced Python','Strengthen your Python foundations with functions, data structures and AI-focused practice.','#4d82ca','/images/unit-7.svg',array['Write reusable Python functions','Work confidently with lists and dictionaries','Use Python to explore simple data'],array['Functions','Lists & dictionaries','Libraries','Data practice'],7,true)
on conflict (id) do update set title=excluded.title,short_title=excluded.short_title,description=excluded.description,color=excluded.color,hero_image_url=excluded.hero_image_url,objectives=excluded.objectives,topics=excluded.topics,position=excluded.position;
select setval(pg_get_serial_sequence('public.units','id'), greatest((select max(id) from public.units),7));

insert into public.lectures (id,unit_id,title,description,duration,topics,position,published) values
('1-1',1,'The AI Project Cycle, Revisited','Connect the five stages of an AI project to a real-world challenge.','12 min',array['Problem scoping','Data acquisition'],1,true),('1-2',1,'From Data to a Model','See how data exploration and modelling fit into the cycle.','16 min',array['Data exploration','Modelling'],2,true),('1-3',1,'Ethics in Artificial Intelligence','Explore fairness, privacy, transparency and accountability.','18 min',array['Fairness','Privacy','Transparency'],3,true),('1-4',1,'Responsible AI in Practice','Use an ethical framework to discuss everyday AI scenarios.','14 min',array['Ethical frameworks','Case study'],4,true),
('2-1',2,'How AI Models Learn','A practical introduction to model training and patterns.','15 min',array['Training data','Patterns'],1,true),('2-2',2,'Supervised Learning','Learn from labelled examples through classification and regression.','18 min',array['Classification','Regression'],2,true),('2-3',2,'Unsupervised Learning','Discover how a model can find groups and structure without labels.','13 min',array['Clustering','Patterns'],3,true),('2-4',2,'Neural Networks: The Basics','Meet layers, weights and activation in an approachable way.','20 min',array['Neural network','Layers'],4,true),
('3-1',3,'Why Evaluate a Model?','Understand the need to check how a model performs on new data.','11 min',array['Evaluation','Generalisation'],1,true),('3-2',3,'Train-Test Split','Keep an honest set of examples for testing model performance.','13 min',array['Training data','Testing data'],2,true),('3-3',3,'Confusion Matrix','Read true and false predictions in a simple grid.','15 min',array['True positive','False positive'],3,true),('3-4',3,'Accuracy, Precision & Recall','Select the right metric for the question you need to answer.','20 min',array['Accuracy','Precision','Recall','F1 score'],4,true),
('4-1',4,'Data and Its Distribution','See what the shape and spread of a dataset can tell you.','14 min',array['Distribution','Spread'],1,true),('4-2',4,'Mean, Median and Mode','Choose a useful measure of central tendency.','15 min',array['Mean','Median','Mode'],2,true),('4-3',4,'Reading Graphs and Charts','Tell a clear, accurate story with visual data.','12 min',array['Charts','Visualisation'],3,true),('4-4',4,'Outliers and Fair Data','Notice unusual values and understand their impact.','13 min',array['Outliers','Data quality'],4,true),
('5-1',5,'How a Computer Sees','Turn an image into pixels and numerical data.','12 min',array['Pixels','Image data'],1,true),('5-2',5,'Image Classification','Understand how a model labels an image.','15 min',array['Classification','Features'],2,true),('5-3',5,'Object Detection','Find and locate objects in a picture.','16 min',array['Detection','Bounding boxes'],3,true),('5-4',5,'Vision Around Us','Explore useful and responsible computer vision applications.','13 min',array['Applications','Ethics'],4,true),
('6-1',6,'What Is NLP?','Meet the AI field that works with human language.','12 min',array['Language','NLP tasks'],1,true),('6-2',6,'Preparing Text for AI','Explore tokens and simple text preprocessing.','14 min',array['Tokens','Preprocessing'],2,true),('6-3',6,'Chatbots and Intent','Learn how a chatbot can identify what someone needs.','17 min',array['Chatbots','Intent'],3,true),('6-4',6,'Sentiment Analysis','Use examples to classify the tone of a sentence.','15 min',array['Sentiment','Classification'],4,true),
('7-1',7,'Functions and Reusable Code','Organise code into clear, reusable functions.','16 min',array['Functions','Parameters'],1,true),('7-2',7,'Lists and Dictionaries','Store and work with useful collections of data.','18 min',array['Lists','Dictionaries'],2,true),('7-3',7,'Working with Data','Use familiar Python patterns to explore small datasets.','20 min',array['Data','Loops'],3,true),('7-4',7,'Python for AI: Mini Project','Put your skills together in a compact AI-inspired activity.','24 min',array['Mini project','Practice'],4,true)
on conflict (id) do update set unit_id=excluded.unit_id,title=excluded.title,description=excluded.description,duration=excluded.duration,topics=excluded.topics,position=excluded.position;

-- Student-safe quiz delivery. The answer key never appears in direct student table access.
create or replace function public.get_student_quiz(p_unit_id integer)
returns jsonb language plpgsql stable security definer set search_path = public
as $$
declare result jsonb;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  select jsonb_build_object('quiz_id',q.id,'title',q.title,'questions',coalesce(jsonb_agg(jsonb_build_object('id',qq.id,'prompt',qq.question_text,'type',qq.question_type,'options',qq.options,'position',qq.position) order by qq.position) filter (where qq.id is not null),'[]'::jsonb))
  into result from public.quizzes q join public.units u on u.id=q.unit_id
  left join public.quiz_questions qq on qq.quiz_id=q.id and qq.published
  where q.unit_id=p_unit_id and q.published and u.published
  group by q.id order by q.created_at desc limit 1;
  return result;
end;
$$;

create or replace function public.submit_student_quiz(p_unit_id integer,p_answers jsonb)
returns jsonb language plpgsql security definer set search_path = public
as $$
declare qrow public.quizzes%rowtype; total integer; correct integer; score integer; feedback jsonb; attempt uuid;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if jsonb_typeof(p_answers) <> 'array' then raise exception 'Answers must be an array'; end if;
  select q.* into qrow from public.quizzes q join public.units u on u.id=q.unit_id where q.unit_id=p_unit_id and q.published and u.published order by q.created_at desc limit 1;
  if qrow.id is null then raise exception 'Quiz not found'; end if;
  select count(*),count(*) filter (where (p_answers->>(qq.position))::integer=qq.correct_option),
    jsonb_agg(jsonb_build_object('id',qq.id,'prompt',qq.question_text,'options',qq.options,'selected_option',coalesce((p_answers->>(qq.position))::integer,-1),'correct_option',qq.correct_option,'correct',(p_answers->>(qq.position))::integer=qq.correct_option,'explanation',qq.explanation) order by qq.position)
  into total,correct,feedback from public.quiz_questions qq where qq.quiz_id=qrow.id and qq.published;
  if total=0 then raise exception 'Quiz has no published questions'; end if;
  score=round((correct::numeric/total)*100)::integer;
  insert into public.quiz_attempts(user_id,quiz_id,unit_id,score_percent,correct_answers,total_questions,answers)
  values(auth.uid(),qrow.id,p_unit_id,score,correct,total,p_answers) returning id into attempt;
  insert into public.learning_activity(user_id,activity_type,entity_type,entity_id,details)
  values(auth.uid(),'quiz_submitted','unit',p_unit_id::text,jsonb_build_object('score_percent',score));
  return jsonb_build_object('attempt_id',attempt,'score_percent',score,'correct_answers',correct,'total_questions',total,'results',feedback);
end;
$$;
grant execute on function public.get_student_quiz(integer) to authenticated;
grant execute on function public.submit_student_quiz(integer,jsonb) to authenticated;
revoke execute on function public.get_student_quiz(integer) from public;
revoke execute on function public.submit_student_quiz(integer,jsonb) from public;

create or replace function public.admin_reorder_units(p_unit_ids integer[])
returns void language plpgsql security definer set search_path = public
as $$
declare offset_value integer; existing_count integer;
begin
  if not public.is_admin() then raise exception 'Administrator access required'; end if;
  select count(*) into existing_count from public.units where course_id='00000000-0000-4000-8000-000000000010';
  if cardinality(p_unit_ids) <> existing_count or exists(select 1 from public.units where course_id='00000000-0000-4000-8000-000000000010' and not (id=any(p_unit_ids))) then
    raise exception 'Provide every current course unit exactly once';
  end if;
  select coalesce(max(position),0)+existing_count+1 into offset_value from public.units where course_id='00000000-0000-4000-8000-000000000010';
  update public.units set position=offset_value+array_position(p_unit_ids,id) where course_id='00000000-0000-4000-8000-000000000010';
  update public.units set position=array_position(p_unit_ids,id)-1 where course_id='00000000-0000-4000-8000-000000000010';
end;
$$;
revoke execute on function public.admin_reorder_units(integer[]) from public;
grant execute on function public.admin_reorder_units(integer[]) to authenticated;

-- RLS
alter table public.classes enable row level security;
alter table public.subjects enable row level security;
alter table public.courses enable row level security;
alter table public.profiles enable row level security;
alter table public.units enable row level security;
alter table public.lectures enable row level security;
alter table public.unit_notes enable row level security;
alter table public.quizzes enable row level security;
alter table public.quiz_questions enable row level security;
alter table public.quiz_attempts enable row level security;
alter table public.sample_papers enable row level security;
alter table public.announcements enable row level security;
alter table public.suggestions enable row level security;
alter table public.lecture_progress enable row level security;
alter table public.learning_activity enable row level security;

drop policy if exists "class catalog read" on public.classes;
create policy "class catalog read" on public.classes for select to authenticated using (true);
drop policy if exists "class admin manage" on public.classes;
create policy "class admin manage" on public.classes for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "subject catalog read" on public.subjects;
create policy "subject catalog read" on public.subjects for select to authenticated using (true);
drop policy if exists "subject admin manage" on public.subjects;
create policy "subject admin manage" on public.subjects for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "course catalog read" on public.courses;
create policy "course catalog read" on public.courses for select to authenticated using (active or public.is_admin());
drop policy if exists "course catalog admin write" on public.courses;
create policy "course catalog admin write" on public.courses for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "profile self or admin read" on public.profiles;
create policy "profile self or admin read" on public.profiles for select to authenticated using (id=auth.uid() or public.is_admin());
drop policy if exists "profile self update" on public.profiles;
create policy "profile self update" on public.profiles for update to authenticated using (id=auth.uid() or public.is_admin()) with check (id=auth.uid() or public.is_admin());
drop policy if exists "profile admin insert" on public.profiles;
create policy "profile admin insert" on public.profiles for insert to authenticated with check (public.is_admin());
drop policy if exists "profile admin delete" on public.profiles;
create policy "profile admin delete" on public.profiles for delete to authenticated using (public.is_admin());

drop policy if exists "units published read" on public.units;
create policy "units published read" on public.units for select to authenticated using (published or public.is_admin());
drop policy if exists "units admin manage" on public.units;
create policy "units admin manage" on public.units for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "lectures published read" on public.lectures;
create policy "lectures published read" on public.lectures for select to authenticated using ((published and exists(select 1 from public.units u where u.id=unit_id and u.published)) or public.is_admin());
drop policy if exists "lectures admin manage" on public.lectures;
create policy "lectures admin manage" on public.lectures for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "unit notes published read" on public.unit_notes;
create policy "unit notes published read" on public.unit_notes for select to authenticated using ((published and exists(select 1 from public.units u where u.id=unit_id and u.published)) or public.is_admin());
drop policy if exists "unit notes admin manage" on public.unit_notes;
create policy "unit notes admin manage" on public.unit_notes for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "quizzes published read" on public.quizzes;
create policy "quizzes published read" on public.quizzes for select to authenticated using ((published and exists(select 1 from public.units u where u.id=unit_id and u.published)) or public.is_admin());
drop policy if exists "quizzes admin manage" on public.quizzes;
create policy "quizzes admin manage" on public.quizzes for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "quiz question admin only" on public.quiz_questions;
create policy "quiz question admin only" on public.quiz_questions for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "quiz attempts private read" on public.quiz_attempts;
create policy "quiz attempts private read" on public.quiz_attempts for select to authenticated using (user_id=auth.uid() or public.is_admin());
drop policy if exists "quiz attempts own insert" on public.quiz_attempts;
-- New attempts are written only by submit_student_quiz after server-side scoring.
drop policy if exists "sample papers published read" on public.sample_papers;
create policy "sample papers published read" on public.sample_papers for select to authenticated using (published or public.is_admin());
drop policy if exists "sample papers admin manage" on public.sample_papers;
create policy "sample papers admin manage" on public.sample_papers for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "announcements published read" on public.announcements;
create policy "announcements published read" on public.announcements for select to authenticated using (published or public.is_admin());
drop policy if exists "announcements admin manage" on public.announcements;
create policy "announcements admin manage" on public.announcements for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "suggestions own insert" on public.suggestions;
create policy "suggestions own insert" on public.suggestions for insert to authenticated with check (user_id=auth.uid());
drop policy if exists "suggestions own read" on public.suggestions;
create policy "suggestions own read" on public.suggestions for select to authenticated using (user_id=auth.uid() or public.is_admin());
drop policy if exists "suggestions admin manage" on public.suggestions;
create policy "suggestions admin manage" on public.suggestions for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "lecture progress own access" on public.lecture_progress;
create policy "lecture progress own access" on public.lecture_progress for all to authenticated using (user_id=auth.uid() or public.is_admin()) with check (user_id=auth.uid() or public.is_admin());
drop policy if exists "learning activity own read" on public.learning_activity;
create policy "learning activity own read" on public.learning_activity for select to authenticated using (user_id=auth.uid() or public.is_admin());
drop policy if exists "learning activity own insert" on public.learning_activity;
create policy "learning activity own insert" on public.learning_activity for insert to authenticated with check (user_id=auth.uid() or public.is_admin());

drop policy if exists "published course files read" on storage.objects;
create policy "published course files read" on storage.objects for select to authenticated using (bucket_id='course-resources' and (public.is_admin() or exists(select 1 from public.unit_notes n where n.storage_path=name and n.published) or exists(select 1 from public.sample_papers p where p.storage_path=name and p.published) or exists(select 1 from public.units u where u.hero_image_url=name and u.published)));
drop policy if exists "course files admin insert" on storage.objects;
create policy "course files admin insert" on storage.objects for insert to authenticated with check (bucket_id='course-resources' and public.is_admin());
drop policy if exists "course files admin update" on storage.objects;
create policy "course files admin update" on storage.objects for update to authenticated using (bucket_id='course-resources' and public.is_admin()) with check (bucket_id='course-resources' and public.is_admin());
drop policy if exists "course files admin delete" on storage.objects;
create policy "course files admin delete" on storage.objects for delete to authenticated using (bucket_id='course-resources' and public.is_admin());
