"use client";

import Link from "next/link";
import { ArrowRight, BookOpen, Check, ChevronRight, CircleHelp, Clock3, FileText, Play, Sparkles, Target, Trophy } from "lucide-react";
import { useEffect, useState } from "react";
import { AppShell } from "@/components/app-shell";
import { ProgressBar } from "@/components/ui";
import { announcements as demoAnnouncements, levelNames } from "@/lib/data";
import { getLearningStats, readState, writeState } from "@/lib/store";
import { useCourseUnits } from "@/lib/hooks";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";

export default function DashboardPage() {
  const courseUnits=useCourseUnits();
  const [state, setState] = useState(readState());
  const [stats, setStats] = useState(()=>getLearningStats(courseUnits));
  useEffect(() => { let alive=true;const refresh=()=>{setState(readState());setStats(getLearningStats(courseUnits));}; window.addEventListener("ai-quest:updated",refresh);const sync=async()=>{const supabase=getSupabaseBrowserClient();if(!supabase)return;const {data:{user}}=await supabase.auth.getUser();if(!user)return;const [progress,quiz,notices,profile]=await Promise.all([supabase.from("lecture_progress").select("lecture_id").eq("user_id",user.id).eq("completed",true),supabase.from("quiz_attempts").select("id,unit_id,score_percent,correct_answers,total_questions,created_at").eq("user_id",user.id).order("created_at",{ascending:false}),supabase.from("announcements").select("id,title,text,created_at").eq("published",true).order("created_at",{ascending:false}),supabase.from("profiles").select("full_name,roll_number,class_name,school").eq("id",user.id).maybeSingle()]);if(!alive)return;const attempts=(quiz.data??[]).map(row=>({id:row.id,unitId:row.unit_id,score:row.score_percent,correct:row.correct_answers,total:row.total_questions,date:row.created_at}));writeState({completed:(progress.data??[]).map(row=>row.lecture_id),attempts,quizScores:attempts.map(row=>row.score),announcements:(notices.data??[]).map(row=>({id:row.id,title:row.title,text:row.text,published:true,createdAt:row.created_at})),profile:profile.data?{name:profile.data.full_name||"Student",roll:profile.data.roll_number||"",className:profile.data.class_name||"10",school:profile.data.school||""}:readState().profile})};sync();return ()=>{alive=false;window.removeEventListener("ai-quest:updated",refresh)}; }, [courseUnits]);
  const activeUnits=courseUnits.filter(unit=>unit.lectures.length>0);
  const currentUnit=activeUnits.find(unit=>!unit.lectures.every(lecture=>stats.completedIds.includes(lecture.id)))??activeUnits[activeUnits.length-1];
  const nextLecture=currentUnit?.lectures.find(lecture=>!stats.completedIds.includes(lecture.id))??currentUnit?.lectures[0];
  const unitPercent=(unitId:number)=>{const unit=courseUnits.find(x=>x.id===unitId);return unit?.lectures.length?Math.round(unit.lectures.filter(l=>stats.completedIds.includes(l.id)).length/unit.lectures.length*100):0;};
  const levelIndex=Math.min(4,Math.floor(stats.overall/20));
  const courseLectureCount=courseUnits.reduce((count,unit)=>count+unit.lectures.length,0);
  const publishedAnnouncements=[...state.announcements.filter(x=>x.published).map(x=>({id:x.id,title:x.title,text:x.text,date:"New",icon:"spark"})),...demoAnnouncements];
  return <AppShell><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="eyebrow">YOUR LEARNING SPACE</div><h1 className="title-lg mt-2">Good to see you, {state.profile.name} <span aria-hidden>👋</span></h1><p className="body-muted mt-2">A new idea is just around the corner. Ready for the next one?</p></div><Link className="btn-secondary" href="/units"><BookOpen size={16}/> Explore units</Link></div>
    <section className="mt-7 grid gap-4 xl:grid-cols-[1.55fr_.85fr]">
      {nextLecture&&currentUnit ? <div className="relative overflow-hidden rounded-[22px] bg-gradient-to-br from-[#405ce0] to-[#6e79e8] p-6 text-white shadow-lg shadow-indigo-100 md:p-7"><div className="relative z-10 max-w-[440px]"><span className="rounded-full bg-white/15 px-3 py-1 text-[10px] font-bold tracking-wide">CONTINUE LEARNING</span><h2 className="mt-4 text-[23px] font-bold leading-tight tracking-tight">{nextLecture.title}</h2><p className="mt-2 text-xs leading-5 text-indigo-100">Unit {currentUnit.id} · {currentUnit.shortTitle}</p><div className="mt-5 flex flex-wrap items-center gap-3"><Link href={`/units/${currentUnit.id}#${nextLecture.id}`} aria-label={`Continue lesson: ${nextLecture.title}`} className="inline-flex items-center gap-2 rounded-xl bg-white px-4 py-2.5 text-xs font-bold !text-indigo-800"><Play size={14} fill="currentColor"/><span style={{color:"#263d9e"}}>Pick up where you left off</span></Link><span className="flex items-center gap-1.5 text-[10px] font-semibold text-indigo-100"><Clock3 size={13}/>{nextLecture.duration}</span></div></div><div className="absolute -right-8 -top-9 grid size-[210px] place-items-center rounded-full border border-white/10 bg-white/5 text-white/70"><div className="grid size-[138px] place-items-center rounded-full border border-white/15 bg-white/5"><BookOpen size={52} strokeWidth={1.2}/></div></div><div className="absolute bottom-0 right-0 h-1 w-full bg-white/15"><div className="h-full bg-emerald-300" style={{width:`${stats.overall}%`}}/></div></div>
       : <div className="card flex min-h-[230px] flex-col justify-center p-6"><span className="grid size-11 place-items-center rounded-2xl bg-indigo-50 text-indigo-600"><BookOpen size={20}/></span><h2 className="mt-4 text-base font-bold">Your first lesson is on its way</h2><p className="body-muted mt-2 max-w-sm text-xs">New video lessons will appear here after your course admin adds and publishes them.</p><Link href="/units" className="btn-secondary mt-5 w-fit text-[10px]">Explore your units <ArrowRight size={13}/></Link></div>}<div className="card p-5"><div className="flex items-start justify-between"><div><span className="badge"><Sparkles size={12} className="mr-1"/>AI JOURNEY</span><h2 className="mt-3 text-lg font-bold">{levelNames[levelIndex]}</h2><p className="mt-1 text-[11px] text-slate-400">Your next milestone: {levelNames[Math.min(4,levelIndex+1)]}</p></div><div className="grid size-11 place-items-center rounded-2xl bg-[#fff7e3] text-amber-500"><Trophy size={21}/></div></div><div className="mt-5"><div className="mb-2 flex justify-between text-[10px]"><span className="font-semibold text-slate-500">Journey progress</span><span className="font-bold text-indigo-600">{stats.overall}%</span></div><ProgressBar value={stats.overall}/></div><div className="mt-5 grid grid-cols-5 gap-1.5">{levelNames.map((name,i)=><div key={name} className="text-center"><div className={`mx-auto grid size-7 place-items-center rounded-full text-[10px] ${i<=levelIndex?"bg-indigo-600 text-white":"bg-slate-100 text-slate-400"}`}>{i<levelIndex?<Check size={14}/>:i+1}</div><div className={`mt-1 text-[8px] leading-3 ${i<=levelIndex?"text-indigo-700 font-bold":"text-slate-400"}`}>{name}</div></div>)}</div><Link href="/progress" className="mt-5 flex items-center justify-between border-t border-slate-100 pt-3 text-[11px] font-bold text-indigo-600">View your AI journey <ArrowRight size={14}/></Link></div>
    </section>
    <section className="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-4">{[{label:"Course progress",value:`${stats.overall}%`,sub:"of your AI course",icon:Target,color:"bg-indigo-50 text-indigo-600"},{label:"Units completed",value:`${stats.doneUnits} / 7`,sub:"keep your streak going",icon:BookOpen,color:"bg-emerald-50 text-emerald-600"},{label:"Lessons completed",value:`${stats.completed} / ${courseLectureCount}`,sub:"one idea at a time",icon:Check,color:"bg-amber-50 text-amber-600"},{label:"Quiz average",value:stats.quizAverage?`${stats.quizAverage}%`:"—",sub:stats.quizAverage?"across your attempts":"ready when you are",icon:CircleHelp,color:"bg-rose-50 text-rose-600"}].map(({label,value,sub,icon:Icon,color})=><div key={label} className="card p-4"><div className="flex items-center justify-between"><span className="text-[10px] font-semibold text-slate-400">{label}</span><span className={`grid size-8 place-items-center rounded-[11px] ${color}`}><Icon size={15}/></span></div><b className="mt-3 block text-[23px] tracking-tight">{value}</b><small className="mt-1 block text-[10px] text-slate-400">{sub}</small></div>)}</section>
    <section className="mt-8 grid gap-5 lg:grid-cols-[1.25fr_.75fr]"><div><div className="section-heading"><div><div className="eyebrow">KEEP THE MOMENTUM</div><h2 className="mt-2 text-lg font-bold">Your units</h2></div><Link href="/units" className="flex items-center gap-1 text-[11px] font-bold text-indigo-600">All units <ChevronRight size={14}/></Link></div><div className="card divide-y divide-slate-100 px-4">{courseUnits.slice(0,4).map(unit=>{const pct=unitPercent(unit.id);return <Link href={`/units/${unit.id}`} key={unit.id} className="flex items-center gap-3 py-3.5"><img src={unit.image} alt="" className="size-12 rounded-xl object-cover"/><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><b className="truncate text-xs">{unit.shortTitle}</b><small className="shrink-0 text-[10px] text-slate-400">{pct}%</small></div><div className="mt-2"><ProgressBar value={pct}/></div></div><ChevronRight size={15} className="text-slate-300"/></Link>})}</div></div>
      <div id="announcements"><div className="section-heading"><div><div className="eyebrow">THE LATEST</div><h2 className="mt-2 text-lg font-bold">Announcements</h2></div></div><div className="card p-4">{publishedAnnouncements.slice(0,3).map(item=><div key={item.id} className="flex gap-3 border-b border-slate-100 py-3 first:pt-0 last:border-0 last:pb-0"><span className="grid size-8 shrink-0 place-items-center rounded-xl bg-amber-50 text-amber-500"><Sparkles size={15}/></span><div><b className="block text-[11px]">{item.title}</b><p className="mt-1 text-[10px] leading-[1.5] text-slate-500">{item.text}</p><small className="mt-1 block text-[9px] text-slate-400">{item.date}</small></div></div>)}</div><Link href="/suggestions" className="mt-4 flex items-center gap-2 rounded-2xl border border-indigo-100 bg-indigo-50/70 p-4 text-[11px]"><span className="grid size-8 place-items-center rounded-xl bg-white text-indigo-500"><FileText size={15}/></span><span className="flex-1"><b className="block">Need help or want to send a message?</b><small className="text-slate-500">Report an issue or message the course team.</small></span><ArrowRight size={15} className="text-indigo-500"/></Link></div></section>
  </AppShell>;
}
